set(VCPKG_POLICY_EMPTY_INCLUDE_FOLDER enabled)

vcpkg_from_git(
  OUT_SOURCE_PATH
  SOURCE_PATH
  URL
  ssh://git@github.com/matterfi/matterfirpc.git
  REF
  7c5adeb5936f62fc9df9b32b858511ea10b527b5
  HEAD_REF
  master)

vcpkg_check_features(
  OUT_FEATURE_OPTIONS FEATURE_OPTIONS
  FEATURES
    casper        MATTERFIRPC_ENABLE_CSPR
    deploy        MATTERFIRPC_ENABLE_DEPLOY
    privacy-cash  MATTERFIRPC_ENABLE_PRIVACY_CASH
)

# Windows: build matterfirpc as shared library so its dependencies are discovered by GET_RUNTIME_DEPENDENCIES
if(VCPKG_TARGET_IS_WINDOWS)
  string(COMPARE EQUAL "${VCPKG_LIBRARY_LINKAGE}" "dynamic" BUILD_SHARED)
  vcpkg_cmake_configure(
    SOURCE_PATH
    "${SOURCE_PATH}"
    OPTIONS
    -DMATTERFIRPC_BUILD_TESTS=OFF
    -DMATTERFIRPC_PEDANTIC_BUILD=OFF
    -DBUILD_SHARED_LIBS=${BUILD_SHARED}
    ${FEATURE_OPTIONS}
    OPTIONS_RELEASE
    -DMATTERFIRPC_DEBUG_BUILD=OFF
    -DMATTERFIRPC_INSTALL_LICENSE=ON
    -DMATTERFIRPC_LICENSE_FILE_NAME=copyright
    OPTIONS_DEBUG
    -DMATTERFIRPC_DEBUG_BUILD=ON
    -DMATTERFIRPC_INSTALL_HEADERS=OFF
    -DMATTERFIRPC_INSTALL_LICENSE=OFF
  )
else()
  vcpkg_cmake_configure(
    SOURCE_PATH
    "${SOURCE_PATH}"
    OPTIONS
    -DMATTERFIRPC_BUILD_TESTS=OFF
    -DMATTERFIRPC_PEDANTIC_BUILD=OFF
    ${FEATURE_OPTIONS}
    OPTIONS_RELEASE
    -DMATTERFIRPC_DEBUG_BUILD=OFF
    -DMATTERFIRPC_INSTALL_LICENSE=ON
    -DMATTERFIRPC_LICENSE_FILE_NAME=copyright
    OPTIONS_DEBUG
    -DMATTERFIRPC_DEBUG_BUILD=ON
    -DMATTERFIRPC_INSTALL_HEADERS=OFF
    -DMATTERFIRPC_INSTALL_LICENSE=OFF
  )
endif()

vcpkg_cmake_install()

vcpkg_cmake_config_fixup(
  PACKAGE_NAME
  "MatterFiRPC"
  NO_PREFIX_CORRECTION
)

file(
  INSTALL "${CMAKE_CURRENT_LIST_DIR}/usage"
  DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}"
)
